version: '3.1'

services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  redis:
    image: redis-stack
    restart: unless-stopped
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
